-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 11:19:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bank-svc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bank-svc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank-svc` DEFAULT CHARACTER SET ucs2 COLLATE ucs2_polish_ci ;
USE `bank-svc` ;

-- -----------------------------------------------------
-- Table `bank-svc`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank-svc`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_acct` VARCHAR(45) NOT NULL,
  `receiver_acct` VARCHAR(45) NOT NULL,
  `amount` BIGINT NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank-svc`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank-svc`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  `balance` BIGINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
